# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2024 MonetDB Foundation

# Run doc tests, unit tests and clippy on various Rust versions
name: Rust versions

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
jobs:

  rust_version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rustversion: [1.85.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4
        with:
          toolchain: ${{ matrix.rustversion }}
          components: clippy

      - run: cargo +${{ matrix.rustversion }} test --lib --examples
      - run: cargo +${{ matrix.rustversion }} test --lib --examples --no-default-features
      - run: cargo +${{ matrix.rustversion }} test --lib --examples --all-features

      - run: cargo +${{ matrix.rustversion }} test --doc
      - run: cargo +${{ matrix.rustversion }} test --doc --no-default-features
      - run: cargo +${{ matrix.rustversion }} test --doc --all-features

      - run: cargo +${{ matrix.rustversion }} clippy --tests -- -D warnings
      - run: cargo +${{ matrix.rustversion }} clippy --tests --no-default-features -- -D warnings
      - run: cargo +${{ matrix.rustversion }} clippy --tests --all-features -- -D warnings

      - run: cargo +${{ matrix.rustversion }} tree
      - run: cargo +${{ matrix.rustversion }} tree --no-default-features
      - run: cargo +${{ matrix.rustversion }} tree --all-features

  big_endian:
    name: big-endian check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4
        with:
          toolchain: stable
          targets: s390x-unknown-linux-gnu
      - run: cargo check --target s390x-unknown-linux-gnu
