# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2024 MonetDB Foundation

# Run doc tests, unit tests and clippy on various Rust versions
name: Rust versions

on:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:

  rust_version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rustversion: [stable, nightly, beta]
    steps:
      - uses: actions/checkout@v4

      - run: rustup install ${{ matrix.rustversion }}

      - run: cargo +${{ matrix.rustversion }} test --lib --examples
      - run: cargo +${{ matrix.rustversion }} test --lib --examples --no-default-features
      - run: cargo +${{ matrix.rustversion }} test --lib --examples --all-features

      - run: cargo +${{ matrix.rustversion }} test --doc
      - run: cargo +${{ matrix.rustversion }} test --doc --no-default-features
      - run: cargo +${{ matrix.rustversion }} test --doc --all-features

      - run: rustup component add --toolchain ${{ matrix.rustversion }} clippy

      - run: cargo +${{ matrix.rustversion }} clippy --tests -- -D warnings
      - run: cargo +${{ matrix.rustversion }} clippy --tests --no-default-features -- -D warnings
      - run: cargo +${{ matrix.rustversion }} clippy --tests --all-features -- -D warnings

      - run: cargo +${{ matrix.rustversion }} tree
      - run: cargo +${{ matrix.rustversion }} tree --no-default-features
      - run: cargo +${{ matrix.rustversion }} tree --all-features
